### ISSUE TITLE
Music didn't play

### ISSUE THREAD

**Issue by makew0rld** [vincentkenny01/spotblock#4]
I understand this isn't a very helpful bug report, but I was not able to play music off Spotify until I disabled your hosts file. In the Android app, clicking play would not create any sound. I will try and find out specifically what domain was causing this, but I was wondering if you could reproduce the issue.

**Comment by IDemixI** [comment]
I'm having the same issue. I believe 1 or more of the recently added blocked URL's is causing this issue. I've had to remove this for now too. Hopefully you figure out which URL and it gets resolved. Keep up the good work! :)

**Comment by vincentkenny01** [comment]
I will do some digging but mine seems to work fine though. I will double check and let you guys know.

**Comment by mupkoo** [comment]
I have to whitelist the following domains to get the macOS app to work

```
ap.spotify.com
dealer.spotify.com
spclient.wg.spotify.com
ww.spotify.com
```

**Comment by teK04** [comment]
> I have to whitelist the following domains to get the macOS app to work
> 
> ```
> ap.spotify.com
> dealer.spotify.com
> spclient.wg.spotify.com
> ww.spotify.com
> ```

If I whitelist these, app works again, but ads also... :-/

**Comment by vincentkenny01** [comment]
ok, so I have removed the following 
spclient.wg.spotify.com
ww.spotify.com
with regards to 
ap.spotify.com and dealer.spotify.com - they did not cause any issues by being blocked. 
can someone give a try....and let me know if you are still facing an issue?

**Comment by teK04** [comment]
Thank you for your investigation. App says "No internet connection". :-/ I'm not able to play any song.

**Comment by OneCricketeer** [comment]
How do you even get to `spotify.com` if you [block it directly](https://github.com/vincentkenny01/spotblock/commit/d3b4d2bdab569659661b61457dbddcd7ae61a941#diff-9aeab829e27266990f352631530f9f8dR1400)?

**Comment by vincentkenny01** [comment]
I have cleaned up the list and now it doesn't block spotify.com and SPC. has anyone tried updated list? 
I get adverts very rarely and that is because of SPC domain as spotify sometimes serve ads from this domain and there is no way around it so far.

**Comment by IDemixI** [comment]
Thanks @vincentkenny01 

I'm going to give this a go now. This is the only additional Blocklist I use with Pi-Hole other than the default ones. I'm not sure if you have some stuff whitelisted that maybe those having issues here do not? Who knows.

Anyway, will provide feedback shortly. Thanks again for keeping this list up to date and all the hard work!

**Comment by OneCricketeer** [comment]
👍 Also trying soon

**Comment by vincentkenny01** [comment]
if you guys prefer. you can use my white list and regex/wildcard list. they are all available on the same page.

**Comment by IDemixI** [comment]
It seems to be working pretty good for me so far. The only ads I've had are the UK Government COVID-19 one. Clear other than that! Don't have to listen to "Trolls the movie" ads anymore 👍

**Comment by vincentkenny01** [comment]
glad to hear that. yes I get the government ones I guess they pushing it through the main spotify domain for wider audience. apart from that it seems solid until they ad some random advert domain that will need blocking in the future. 

just fyi if you guys check out other lists you will see less ads on youtube and uk tv on demand.

**Comment by fabge** [comment]
@vincentkenny01 

>  have cleaned up the list and now it doesn't block spotify.com and SPC

were exactly did you clean up the list? the last commit was 10 days ago, and I can still see `spotify.com` in the list, or am I missing something?

**Comment by vincentkenny01** [comment]
> @vincentkenny01
> 
> > have cleaned up the list and now it doesn't block spotify.com and SPC
> 
> were exactly did you clean up the list? the last commit was 10 days ago, and I can still see `spotify.com` in the list, or am I missing something?

Do you have issues when using this list at the moment? Can you be specific what exactly isn't working for you?

**Comment by OneCricketeer** [comment]
You didn't really answer

> How do you even get to spotify.com  ?

 
For example, can't get to the web player <https://open.spotify.com/> , can't even get to the web page to download spotify. Pretty sure `brew cask install spotify` would be blocked as well, no?

**Comment by vincentkenny01** [comment]
the only domain whitelisted in my white list is spclient.wg.spotify.com
I don't have any issues with accessing spotify either open or otherwise. are you sure it's not some other list causing you issues? mine seem to work fine and there are occasionally ads through spclient.wg.spotify.com domain but if I block this one, the app stops to work.

**Comment by JavanXD** [comment]
i've tried the following to whitelist:
```
apresolve.spotify.com
audio-sp.spotify.com
ff.video-ak.cdn.spotify.com
spclient.wg.spotify.com
```
it works. 
can you publish a whitelist only for spotify and don't mix it with the other whitelists?

**Comment by OneCricketeer** [comment]
> only for spotify

Isn't that what this is? https://github.com/vincentkenny01/spotblock/blob/master/spotify

**Comment by JavanXD** [comment]
> Isn't that what this is?

the list you are referring to is the blacklist. 

the spotify whitelist entrys are mixed with others.

**Comment by JavanXD** [comment]
Found another working spotify adlists:
https://raw.githubusercontent.com/dfederlein/dnsbl-dfed/master/spotifyads.txt
works with Pi-hole

**Comment by vincentkenny01** [comment]
the list seems to work alright for me and some other users.
